manifest:
  defaults:
    revision: v0.2
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    # - name: caelum_module
    #   url-base: https://github.com/lindaazhao/
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    # - name: caelum-module
    #   remote: caelum_module
    #   revision: main
  self:
    path: config
